stages:
  - build
  - test

variables:
  DEFAULT_FEDORA_IMAGE: registry.gitlab.com/kicad/kicad-ci/source_containers/master/fedora:40

default:
  image:
    name: $DEFAULT_FEDORA_IMAGE
    entrypoint: ["/bin/sh", "-c"]

include:
  - local: '/.gitlab/Fedora-Linux-CI.yml'
  - local: '/.gitlab/docs.yml'
