"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

This program source code file is part of KiCad, a free EDA CAD application.

Copyright (C) 2024 KiCad Developers, see AUTHORS.txt for contributors.

This program is free software: you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation, either version 3 of the License, or (at your
option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program.  If not, see <http://www.gnu.org/licenses/>.
"""
import builtins
import collections.abc
from .. import common
import google.protobuf.any_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GetSchematicInfo(google.protobuf.message.Message):
    """Proof of Concept: Get basic schematic information"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SCHEMATIC_FIELD_NUMBER: builtins.int

    @property
    def schematic(self) -> common.types.base_types_pb2.DocumentSpecifier:
        ...

    def __init__(self, *, schematic: common.types.base_types_pb2.DocumentSpecifier | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['schematic', b'schematic']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['schematic', b'schematic']) -> None:
        ...
global___GetSchematicInfo = GetSchematicInfo

@typing.final
class SchematicInfoResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PROJECT_NAME_FIELD_NUMBER: builtins.int
    SHEET_COUNT_FIELD_NUMBER: builtins.int
    SYMBOL_COUNT_FIELD_NUMBER: builtins.int
    NET_COUNT_FIELD_NUMBER: builtins.int
    SHEET_NAMES_FIELD_NUMBER: builtins.int
    project_name: builtins.str
    sheet_count: builtins.int
    symbol_count: builtins.int
    net_count: builtins.int

    @property
    def sheet_names(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        ...

    def __init__(self, *, project_name: builtins.str=..., sheet_count: builtins.int=..., symbol_count: builtins.int=..., net_count: builtins.int=..., sheet_names: collections.abc.Iterable[builtins.str] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['net_count', b'net_count', 'project_name', b'project_name', 'sheet_count', b'sheet_count', 'sheet_names', b'sheet_names', 'symbol_count', b'symbol_count']) -> None:
        ...
global___SchematicInfoResponse = SchematicInfoResponse

@typing.final
class GetSchematicItems(google.protobuf.message.Message):
    """Get schematic items (wires, junctions, labels)"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SCHEMATIC_FIELD_NUMBER: builtins.int
    ITEM_IDS_FIELD_NUMBER: builtins.int
    TYPES_FIELD_NUMBER: builtins.int

    @property
    def schematic(self) -> common.types.base_types_pb2.DocumentSpecifier:
        ...

    @property
    def item_ids(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[common.types.base_types_pb2.KIID]:
        """Empty = get all"""

    @property
    def types(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[common.types.enums_pb2.KiCadObjectType.ValueType]:
        """Filter by type"""

    def __init__(self, *, schematic: common.types.base_types_pb2.DocumentSpecifier | None=..., item_ids: collections.abc.Iterable[common.types.base_types_pb2.KIID] | None=..., types: collections.abc.Iterable[common.types.enums_pb2.KiCadObjectType.ValueType] | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['schematic', b'schematic']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['item_ids', b'item_ids', 'schematic', b'schematic', 'types', b'types']) -> None:
        ...
global___GetSchematicItems = GetSchematicItems

@typing.final
class GetSchematicItemsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ITEMS_FIELD_NUMBER: builtins.int
    TOTAL_COUNT_FIELD_NUMBER: builtins.int
    total_count: builtins.int

    @property
    def items(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.any_pb2.Any]:
        ...

    def __init__(self, *, items: collections.abc.Iterable[google.protobuf.any_pb2.Any] | None=..., total_count: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['items', b'items', 'total_count', b'total_count']) -> None:
        ...
global___GetSchematicItemsResponse = GetSchematicItemsResponse

@typing.final
class CreateSchematicItems(google.protobuf.message.Message):
    """Create simple schematic items (junction, wire, label)"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SCHEMATIC_FIELD_NUMBER: builtins.int
    ITEMS_FIELD_NUMBER: builtins.int

    @property
    def schematic(self) -> common.types.base_types_pb2.DocumentSpecifier:
        ...

    @property
    def items(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.any_pb2.Any]:
        ...

    def __init__(self, *, schematic: common.types.base_types_pb2.DocumentSpecifier | None=..., items: collections.abc.Iterable[google.protobuf.any_pb2.Any] | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['schematic', b'schematic']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['items', b'items', 'schematic', b'schematic']) -> None:
        ...
global___CreateSchematicItems = CreateSchematicItems

@typing.final
class CreateSchematicItemsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CREATED_IDS_FIELD_NUMBER: builtins.int
    ERRORS_FIELD_NUMBER: builtins.int

    @property
    def created_ids(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[common.types.base_types_pb2.KIID]:
        ...

    @property
    def errors(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Any creation errors"""

    def __init__(self, *, created_ids: collections.abc.Iterable[common.types.base_types_pb2.KIID] | None=..., errors: collections.abc.Iterable[builtins.str] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['created_ids', b'created_ids', 'errors', b'errors']) -> None:
        ...
global___CreateSchematicItemsResponse = CreateSchematicItemsResponse